service: s3-image-uploader

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

custom:
  imageUploadBucketName: ${self:service}-bucket-${self:provider.stage}

resources:
  Resources:
    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.imageUploadBucketName}
        AccessControl: PublicRead # Private
